version: '3.8'
networks:
    computo:
      driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8007:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - computo

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./db:/var/lib/mysql
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: computo
            MYSQL_USER: computo
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - computo

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
        ports:
            - "9007:9000"
        networks:
            - computo

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8087:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=3306
      networks:
        - computo
